### ISSUE TITLE
能在Mobile设备上跑吗

### ISSUE THREAD

**Issue by DyncEric** [RogerTeng/DTLN_AEC#1]
性能怎么样

**Comment by RogerTeng** [comment]
沒有特別在手機上測過
TensorFlow lite在手機上有用指令集加速
但實際計算量可能要上機測看看才知道

計算量不夠的話 可以改用[PiDTLN](https://github.com/SaneBow/PiDTLN)的模型
這位作者是在Raspberry Pi 3B+上測試的
code裡面的tensor input順序要改過才能跑
效果比原始模型差了一點點

DTLN-AEC原作者有提供三個不同參數的模型
我自己測試除了最小的128明顯比較差以外
256/512在大部分的環境下沒有太大差異

跟WebRTC的AEC3相比，DTLN-AEC是比較好的
人聲還原比較自然
但DTLN-AEC對near end/far end的延遲比AEC3敏感

**Comment by RogerTeng** [comment]
補充 我自己測試的效果排名：
DTLN-AEC 512 > DTLN-AEC 256 >= PiDTLN 512 = DTLN-AEC 128 > WebRTC AEC3 = PiDTLN 256

**Comment by DyncEric** [comment]
好的。感谢答复
